#ifndef POCKETSHELF_APP_ACTIONS_H
#define POCKETSHELF_APP_ACTIONS_H
enum {
  ACTION_BACK = 1,
  ACTION_CANCEL = 2,
  ACTION_SEARCH = 10,
  ACTION_POPULAR = 11,
  ACTION_DOWNLOADS = 12,
  ACTION_SETTINGS = 13,
  ACTION_ADDRESS = 20,
  ACTION_FORMAT = 22,
  ACTION_SIGNOUT = 23,
  ACTION_EMAIL = 24,
  ACTION_PASSWORD = 25,
  ACTION_LOGIN = 26,
  ACTION_REPAIR = 27,
  ACTION_RETRY = 34,
  ACTION_DOWNLOAD = 40,
  ACTION_OPEN = 41,
  ACTION_DESCRIPTION = 42,
  ACTION_INFO = 43,
  ACTION_TEXT_PREVIOUS = 44,
  ACTION_TEXT_NEXT = 45,
  BOOK_ACTION = 1000,
  LOCAL_ACTION = 1000000
};
#endif
